kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: qa
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml
- horizontalpodautoscaler.yaml
- kustomization.yaml
resources:
- ../../base/drone-api-test-1
