---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: sso-account-sponsor-reconcile
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers: null
  schedule: ""
status: {}
