kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- horizontalpodautoscaler.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- horizontalpodautoscaler.yaml
- kustomization.yaml
