apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: sso-oauth-authority-padmin1-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: kube.padmin1.sharecare.com
  project: default
  source:
    path: padmin1/prod/sso-oauth-authority
    repoURL: https://github.com/Sharecare/SSO-OAuth-Authority
    targetRevision: HEAD
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        path: ""
        repoURL: ""
    status: ""
