kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: dev
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml
- horizontalpodautoscaler.yaml
- kustomization.yaml
resources:
- ../../base/sso-static-content
- post-sync-hook.yaml
- sync-fail-hook.yaml
