apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  creationTimestamp: null
  name: post-sync-hook-sso-static-content
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CREATION_TIMESTAMP
          value: "1581434573975"
        - name: INSTANCE
          value: static.dev.jay.sharecare.com
        - name: REGION
          value: US
        - name: MAESTRO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MAESTRO_CREATION_TIMESTAMP
          value: "1581434573975"
        - name: MAESTRO_INSTANCE
          value: static.dev.jay.sharecare.com
        - name: MAESTRO_HOSTS
          value: static.dev.jay.sharecare.com
        - name: MAESTRO_REGION
          value: US
        - name: MAESTRO_ALL_REGIONS
          value: US
        - name: MAESTRO_SERVICE
          value: sso-static-content
        - name: MAESTRO_BUILD
          value: f1a10ad1-772c-4e99-88bb-0fe1ef3ea43d
        - name: ARGO_EVENT_STATUS
          value: deployed
        - name: K8S_CLUSTER_ID
          value: k8s2
        - name: SSO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SSO_PASSWORD
              name: argo-resource-hook
        - name: SSO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SSO_CLIENT_SECRET
              name: argo-resource-hook
        image: nexus.admin.sharecare.com/maestro-deployments-resource-hook-plugin
        imagePullPolicy: IfNotPresent
        name: post-sync-hook-sso-static-content
        resources: {}
      imagePullSecrets:
      - name: nexus
      restartPolicy: Never
