kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: prod
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml
- horizontalpodautoscaler.yaml
resources:
- ../../base/articles-api
