apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: padmin1-prod-sso-sso-oauth-bar
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: padmin1/prod/sso-oauth-authority
    repoURL: https://github.com/sc-test-organization/kubes-deployment-testing
    targetRevision: HEAD
  syncPolicy:
    automated: {}