apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pencho
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: padmin1/prod/sso-authorization
    repoURL: https://github.com/sc-test-organization/kubes-deployment-testing
    targetRevision: HEAD
  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
