apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pscprod1-prod-sso-authorization
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pscprod1/prod/sso-authorization
    repoURL: https://github.com/sc-test-organization/kubes-deployment-testing
    targetRevision: HEAD
  syncPolicy:
    automated: {}