kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: stage
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml
- horizontalpodautoscaler.yaml
- kustomization.yaml
resources:
- ../../base/sso-oauth-authority
