typemeta:
  kind: Application
  apiversion: argoproj.io/v1alpha1
objectmeta:
  name: drone-api-test-1-padmin1-qa
  generatename: ""
  namespace: argocd
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "2020-01-24T11:20:00.059001-05:00"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  clustername: ""
  managedfields: []
spec:
  source:
    repourl: https://github.com/sc-test-organization/kubes-deployment-testing
    path: padmin1/qa/drone-api-test-1
    targetrevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  project: default
