apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  creationTimestamp: null
  name: post-sync-hook-drone-api-test-2
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_SERVICE_HOST
          value: http://localhost:3000
        - name: MAESTRO_SERVICE
          value: drone-api-test-2
        - name: MAESTRO_DEPLOYMENT_ID
          value: 0561a7bc-97e5-4261-8a4b-a5b4b0c529db
        - name: ARGO_EVENT_STATUS
          value: deployed
        - name: K8S_CLUSTER_ID
          value: padmin1
        - name: SSO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SSO_PASSWORD
              name: argo-resource-hook
        - name: SSO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SSO_CLIENT_SECRET
              name: argo-resource-hook
        image: nexus.admin.sharecare.com/maestro-deployments-resource-hook-plugin:1.3.9
        imagePullPolicy: IfNotPresent
        name: post-sync-hook-drone-api-test-2
        resources: {}
      imagePullSecrets:
      - name: nexus
      restartPolicy: Never
