apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app: drone-api-test-2
    env: qa
    maestro: "true"
    maestroversion: v2
    team: maestro
  name: drone-api-test-2
  namespace: qa
spec:
  encryptedData:
    MAESTRO_MONGO_DRONEAPITEST2_PASSWORD: AgCzq4WnCwB1YnHoAKVkQh85zVKAahoPP4cJP0s/QyRVO8c3HF3/9V2evd69nf/Kh2N4VXY7Bj0TpaRd+hGT7m6dhAQdY/Av34RxNHI/AyI4lO5biRS71++Er28CYktNd7wruCx0dT8WPr07mbB+0mP/SJfeHJListf9S/Wt/gOluWTv7+vAGGIYoPM2nTpx0vovfqFUKz+9VYTRU6N9Nc9F3X7zIOlWJkB2RGb5UkoBOn6Q9f2QfBadnPQ/cill3oeAWq7qMUtqpU6uLimUoMUau3K+sBOi9tuvAxOFGbqUhcbTJ7c+/xbJC28qrSTxw/3qG7h33nYuiNLEkBd11jpoqDduNb/3wvylvZYOcOIOfppW+oL5cTiCROllemytp1kFQI5WCT1fUugmldCYrWXFDZ79SDMLY5z2LBxiyI5P114qv/GPq4PYpsAjp+7pmnBFvmVHVS3vjqk2KZrUkMu5uExEYO3Y/wJ3OmR2LEx6mt9oc267KlW+4bZSRg14GoURJSRPcugHPv3GOZKgTGzdm2mZDpQ7U/70/wmCab47JmqSc+OGWRte4gMA1FxmBCZdziwzX3bvwT5kvaZutixnj/BRensPAHPgM881UW8dyli4HSM3Vbu0ADk9eVpsU85wLJEkVtOYFWJt7/PR/ndZwTdkHU3oIdS34c0bzEayXEJKV3g2ljDm23muGqViDltMJfXqLJtC26BOW0THmgiND20Lf3HbtZUZuFTyFAgVRxBhzx0=
    MAESTRO_MONGO_DRONEAPITEST2_USERNAME: AgBbH1pEGK6eTnDf+UQo/V26p7VrEJHMRiVZvRrGSSVNALHF1zMD7oXcFzYTgZQxpTjz84nAiI5Z0iFvlLalLipY/a37B21Kr7EqgY9PxNMQciA0v7vrvO+v/bHMjl6+B13cWfkv+9RftrgfnqWs+/2/vxBWSKRWXvK7BAGajQ5dN+bID/ram3/dy2SU/fB95GkocYtRtlIe/+ZROC1kRqScJjpWBGMrL3VHMGXUNDf9Hmb6RjblBCeGaTf+r47ZEpf9/loFOspORI2CdQAmnVJRQuOrJjJtnOn3b0oyLNKT3sU/AttcuC1leWvQS4h0xeKLfAPzHXc9Eys84pNwwbte0d/nTn49QYPbe2irLtD2wXTSOQppXlCt4OpY209NCZUaIxjT/DzXGra05mzkJT31PmI+1qHq6ytsrwvVmmNTP+UNZZ6T0waGQplJ2tY4W43zXoOOFVK8TTsZbPi2qtK5TkOMNnQMPUOGRFp39Myk8/qw4OdDQ8z9zolr5in0E6BSSllx3uUmBoYvLErwb8p49gYhSdggLshaoXAvPrXMDkFOlRw7ZBgojRsUbcOC9c6XMehbPC/COKilkn9J0wbJDlECpyg91MM9XSs/fWvyHMTAQENtYMcmkJJ7ddfwYc2PqGCCf+oMddqJQuDE4sYDf0ArvjZR+MlrQZwuF8DoaMeXn3xX044m4QTbR9z1Jg+brmtkIHQR9aQvRAVYtcvA8QPpQ6ox4Leyz04viMs=
    SSO_CLIENT_SECRET: AgBOiU/hM9eH2u81kIAVRlc0jngaJZ7ZX5EvT/77LATPu/bzyRUSB/1EvbzZXHyEWEc0nMHfeq8JXolVGhA5AV/+NhwldUGud3O2zIewCb9IcHJEyps3/QAWmLQD7Wtg5F9zHhL4RlMpBCpLVoikHYD/ShGoOQVBuWrSvYQuTalwgbizbtqOaZWwR9dCFpkr0WmFeXdzEMHfpVILaeHBRVEKwP1LkYII9OnoR/4yNoW/LarjsbQPumEdxN2LXk+ofZegCNOsO2wYiKk5+EC4mGEboYh7V0l/4oGyWMIG7o3Uh5ooe0hYHFY8XVkcYtOu88uUqQBzLtaK3LeRP7iNP/p4Wxz/h+piD0+rCJ2fLKNmR/T6hGj0juPoh8H8+FZABL5EEzg6MAG56ZDVyUGv/3CpG8R6V2dElqZDDatRoMGGra4WYFpy8R30O+kK2mYegaOpz7yz2CeBFYEU6tlv9kHu2MzFqHt762IBkI2OD9TSBpiHwAdY3dh3taesd8+vtq6sLXy5M9NIDlpectkY0PDnHUZJnSgxWyJX19P7gaBKvFx9R6ljmUFmTL0Dv66m9HU1MPf7GIb19AJ1HWolk/hx7d+vyAz7AaU+VHt+MZ4FMeIOOb71rPkZd22wUXQbQb+6S+BZBf6J9Dx/cNhIhNLtRFFsJiVxjqJqJs7gPnYnpQ54tI17NB8yfNADUFPmzljhHKE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drone-api-test-2
        env: qa
        maestro: "true"
        maestroversion: v2
        team: maestro
      name: drone-api-test-2
      namespace: qa
