apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: audience-segmentation-service-pscprod1-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: kube.pscprod1.sharecare.com
  project: default
  source:
    path: pscprod1/prod/audience-segmentation-service
    repoURL: https://github.com/Sharecare/audience-segmentation-service
    targetRevision: HEAD
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        path: ""
        repoURL: ""
    status: ""
