apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drone-auth-config-plugin
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: drone-auth-config-plugin
  targetCPUUtilizationPercentage: 50