apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: default-maestro-base
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: default-maestro-base
  targetCPUUtilizationPercentage: 50

