apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2019-10-31T20:03:38Z"
  labels:
    app: sso-account
    env: dev
    maestro: "true"
    team: sso
  name: sso-account
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-account
      env: dev
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: app-dev-sso-account
      creationTimestamp: null
      labels:
        app: sso-account
        env: dev
        maestro: "true"
        team: sso
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sso-account
                  env: dev
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sso-account
                  env: dev
              topologyKey: kubernetes.io/hostname
            weight: 10
      containers:
      - env:
        - name: SSO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SSO_CLIENT_SECRET
              name: SSO_CLIENT_SECRET
        - name: APP_CRYPTO_SECRET
          valueFrom:
            secretKeyRef:
              key: APP_CRYPTO_SECRET
              name: APP_CRYPTO_SECRET
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: AWS_SECRET_ACCESS_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: AWS_ACCESS_KEY_ID
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: getMetadata.namespace
        - name: CREATION_TIMESTAMP
          value: "1572552218838790000"
        - name: INSTANCE
          value: dev.sharecare.com.au
        - name: REGION
          value: us-east-1
        - name: MAESTRO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: getMetadata.namespace
        - name: MAESTRO_CREATION_TIMESTAMP
          value: "1572552218838790000"
        - name: MAESTRO_INSTANCE
          value: dev.sharecare.com.au
        - name: MAESTRO_REGION
          value: us-east-1
        image: nexus.admin.sharecare.com/sso-account:4.37.0-425
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /healthcheck?livenessProbe
            port: 9002
            scheme: http
          initialDelaySeconds: 30
          periodSeconds: 5
        name: sso-account
        ports:
        - containerPort: 9002
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /healthcheck?readinessProbe
            port: 9002
            scheme: http
          initialDelaySeconds: 15
          periodSeconds: 10
        resources: {}
        volumeMounts:
        - mountPath: /app/secrets
          name: app-secrets
          readOnly: true
      imagePullSecrets:
      - name: nexus
status: {}
