apiVersion: apps/v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probepath: /healthcheck
  creationTimestamp: null
  labels:
    app: sc3-scheduler
    env: prod
    maestro: "true"
    team: berlin-server
  name: sc3-scheduler
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sc3-scheduler
status:
  loadBalancer: {}
